/*	File minos_header.h
	Header of the project generated by CMake.
*/

constexpr char* projectHeader = 
R"(***************************************************************
*               MINimal Optimal-control Solver                *
*                        Version 1.0.0                        *
* Copyright (C) 2024 Stefano Lovato <stefano.lovato@unipd.it> *
***************************************************************)";